export interface GalleryItem {
  label: string;
  href: string;
  category?: string;
  metadata?: {
    camera: string;
    lens: string;
    focalLength: string;
    aperture: string;
    shutterSpeed: string;
    iso: string;
  };
}

// This file is auto-generated by scripts/build-gallery.js
// Run: npm run build:gallery to regenerate
export const galleryItems: GalleryItem[] = [
  {
    "label": "DSC03013",
    "href": "/gallery/street/DSC03013.jpg",
    "category": "all",
    "originalCategory": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/1000s",
      "iso": "25600"
    }
  },
  {
    "label": "DSC03555",
    "href": "/gallery/street/DSC03555.jpg",
    "category": "all",
    "originalCategory": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/160s",
      "iso": "2000"
    }
  },
  {
    "label": "DSC03564",
    "href": "/gallery/street/DSC03564.jpg",
    "category": "all",
    "originalCategory": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/160s",
      "iso": "2000"
    }
  },
  {
    "label": "DSC03629",
    "href": "/gallery/street/DSC03629.jpg",
    "category": "all",
    "originalCategory": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.5",
      "shutterSpeed": "1/800s",
      "iso": "200"
    }
  },
  {
    "label": "DSC03647",
    "href": "/gallery/street/DSC03647.jpg",
    "category": "all",
    "originalCategory": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.5",
      "shutterSpeed": "1/500s",
      "iso": "400"
    }
  },
  {
    "label": "DSC03763",
    "href": "/gallery/street/DSC03763.jpg",
    "category": "all",
    "originalCategory": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.5",
      "shutterSpeed": "1/160s",
      "iso": "2500"
    }
  },
  {
    "label": "DSC09113",
    "href": "/gallery/street/DSC09113.jpg",
    "category": "all",
    "originalCategory": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/50s",
      "iso": "1250"
    }
  },
  {
    "label": "DSC09404",
    "href": "/gallery/street/DSC09404.jpg",
    "category": "all",
    "originalCategory": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/30s",
      "iso": "2500"
    }
  },
  {
    "label": "DSC04696",
    "href": "/gallery/landscape/DSC04696.jpg",
    "category": "all",
    "originalCategory": "landscape",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "24-70mm F2.8 DG DN II | Art 024",
      "focalLength": "51mm",
      "aperture": "f/5.6",
      "shutterSpeed": "1/60s",
      "iso": "125"
    }
  },
  {
    "label": "DSC04697",
    "href": "/gallery/landscape/DSC04697.jpg",
    "category": "all",
    "originalCategory": "landscape",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "24-70mm F2.8 DG DN II | Art 024",
      "focalLength": "55mm",
      "aperture": "f/5.6",
      "shutterSpeed": "1/60s",
      "iso": "100"
    }
  },
  {
    "label": "DSC04703",
    "href": "/gallery/landscape/DSC04703.jpg",
    "category": "all",
    "originalCategory": "landscape",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "24-70mm F2.8 DG DN II | Art 024",
      "focalLength": "62mm",
      "aperture": "f/5.6",
      "shutterSpeed": "1/80s",
      "iso": "100"
    }
  },
  {
    "label": "DSC03729",
    "href": "/gallery/architecture/DSC03729.jpg",
    "category": "all",
    "originalCategory": "architecture",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.8",
      "shutterSpeed": "1/500s",
      "iso": "100"
    }
  },
  {
    "label": "DSC05058",
    "href": "/gallery/bw/DSC05058.jpg",
    "category": "all",
    "originalCategory": "bw",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "24-70mm F2.8 DG DN II | Art 024",
      "focalLength": "24mm",
      "aperture": "f/9",
      "shutterSpeed": "1/50s",
      "iso": "100"
    }
  },
  {
    "label": "DSC03013",
    "href": "/gallery/street/DSC03013.jpg",
    "category": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/1000s",
      "iso": "25600"
    }
  },
  {
    "label": "DSC03013",
    "href": "/gallery/street/DSC03013.jpg",
    "category": "bw",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/1000s",
      "iso": "25600"
    }
  },
  {
    "label": "DSC03555",
    "href": "/gallery/street/DSC03555.jpg",
    "category": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/160s",
      "iso": "2000"
    }
  },
  {
    "label": "DSC03555",
    "href": "/gallery/street/DSC03555.jpg",
    "category": "bw",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/160s",
      "iso": "2000"
    }
  },
  {
    "label": "DSC03564 2",
    "href": "/gallery/street/DSC03564-2.jpg",
    "category": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/160s",
      "iso": "2000"
    }
  },
  {
    "label": "DSC03564",
    "href": "/gallery/street/DSC03564.jpg",
    "category": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/160s",
      "iso": "2000"
    }
  },
  {
    "label": "DSC03564",
    "href": "/gallery/street/DSC03564.jpg",
    "category": "bw",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/160s",
      "iso": "2000"
    }
  },
  {
    "label": "DSC03629 2",
    "href": "/gallery/street/DSC03629-2.jpg",
    "category": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.5",
      "shutterSpeed": "1/800s",
      "iso": "200"
    }
  },
  {
    "label": "DSC03629 2",
    "href": "/gallery/street/DSC03629-2.jpg",
    "category": "bw",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.5",
      "shutterSpeed": "1/800s",
      "iso": "200"
    }
  },
  {
    "label": "DSC03629",
    "href": "/gallery/street/DSC03629.jpg",
    "category": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.5",
      "shutterSpeed": "1/800s",
      "iso": "200"
    }
  },
  {
    "label": "DSC03647",
    "href": "/gallery/street/DSC03647.jpg",
    "category": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.5",
      "shutterSpeed": "1/500s",
      "iso": "400"
    }
  },
  {
    "label": "DSC03647",
    "href": "/gallery/street/DSC03647.jpg",
    "category": "bw",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.5",
      "shutterSpeed": "1/500s",
      "iso": "400"
    }
  },
  {
    "label": "DSC03763",
    "href": "/gallery/street/DSC03763.jpg",
    "category": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.5",
      "shutterSpeed": "1/160s",
      "iso": "2500"
    }
  },
  {
    "label": "DSC03763",
    "href": "/gallery/street/DSC03763.jpg",
    "category": "bw",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.5",
      "shutterSpeed": "1/160s",
      "iso": "2500"
    }
  },
  {
    "label": "DSC03833 2",
    "href": "/gallery/street/DSC03833-2.jpg",
    "category": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.5",
      "shutterSpeed": "1/1250s",
      "iso": "1600"
    }
  },
  {
    "label": "DSC03833 2",
    "href": "/gallery/street/DSC03833-2.jpg",
    "category": "bw",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.5",
      "shutterSpeed": "1/1250s",
      "iso": "1600"
    }
  },
  {
    "label": "DSC09113",
    "href": "/gallery/street/DSC09113.jpg",
    "category": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/50s",
      "iso": "1250"
    }
  },
  {
    "label": "DSC09113",
    "href": "/gallery/street/DSC09113.jpg",
    "category": "bw",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/50s",
      "iso": "1250"
    }
  },
  {
    "label": "DSC09404",
    "href": "/gallery/street/DSC09404.jpg",
    "category": "street",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/30s",
      "iso": "2500"
    }
  },
  {
    "label": "DSC09404",
    "href": "/gallery/street/DSC09404.jpg",
    "category": "bw",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "----",
      "focalLength": "Unknown",
      "aperture": "Unknown",
      "shutterSpeed": "1/30s",
      "iso": "2500"
    }
  },
  {
    "label": "DSC04696",
    "href": "/gallery/landscape/DSC04696.jpg",
    "category": "landscape",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "24-70mm F2.8 DG DN II | Art 024",
      "focalLength": "51mm",
      "aperture": "f/5.6",
      "shutterSpeed": "1/60s",
      "iso": "125"
    }
  },
  {
    "label": "DSC04697",
    "href": "/gallery/landscape/DSC04697.jpg",
    "category": "landscape",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "24-70mm F2.8 DG DN II | Art 024",
      "focalLength": "55mm",
      "aperture": "f/5.6",
      "shutterSpeed": "1/60s",
      "iso": "100"
    }
  },
  {
    "label": "DSC04703",
    "href": "/gallery/landscape/DSC04703.jpg",
    "category": "landscape",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "24-70mm F2.8 DG DN II | Art 024",
      "focalLength": "62mm",
      "aperture": "f/5.6",
      "shutterSpeed": "1/80s",
      "iso": "100"
    }
  },
  {
    "label": "DSC03729",
    "href": "/gallery/architecture/DSC03729.jpg",
    "category": "architecture",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.8",
      "shutterSpeed": "1/500s",
      "iso": "100"
    }
  },
  {
    "label": "DSC03647 2",
    "href": "/gallery/abstract/DSC03647-2.jpg",
    "category": "abstract",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "FE 40mm F2.5 G",
      "focalLength": "40mm",
      "aperture": "f/2.5",
      "shutterSpeed": "1/500s",
      "iso": "400"
    }
  },
  {
    "label": "DSC05058",
    "href": "/gallery/bw/DSC05058.jpg",
    "category": "bw",
    "metadata": {
      "camera": "SONY ILCE-7M3",
      "lens": "24-70mm F2.8 DG DN II | Art 024",
      "focalLength": "24mm",
      "aperture": "f/9",
      "shutterSpeed": "1/50s",
      "iso": "100"
    }
  }
];

export const categories = [
  { value: "all", label: "All" },
  { value: "street", label: "Street Photography" },
  { value: "landscape", label: "Landscape" },
  { value: "architecture", label: "Architecture" },
  { value: "portrait", label: "Portrait" },
  { value: "abstract", label: "Abstract" },
  { value: "bw", label: "B&W" }
];
