name: ci

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - run: yarn install --frozen-lockfile

      - run: yarn build
        env:
          NOTION_API_KEY: ${{secrets.NOTION_API_KEY}}
          DATABASE_ID: ${{secrets.DATABASE_ID}}
